### ISSUE TITLE
Purchases doesnt cost anything

### ISSUE THREAD

**Issue by MortyHD** [alex-prog/TheBankErrorReport#6]
When a purchase has been performed the offer is removed but the amount is not withdrawn from ones account

**Comment by Andrei997** [comment]
Do you want to be rich or not ? :)

**Comment by alex-prog** [comment]
Hej...This is because your currency and the one you are buy has the same exchange rate. 

eg:
exchange rate -> 100 xxx = 100 yyy
offer             -> xxx will sell 5xxx
buy               -> yyy will buy 5xxx
Since the rate is the same, you need to pay 5xxx (this will be 5yyy), and you will get 5xxx = 5yyy.

So nothing will happen
