### ISSUE TITLE
Purchases doesn't register on the buyers account

### ISSUE THREAD

**Issue by GassyWhale** [alex-prog/TheBankErrorReport#7]
Purchases are either not registered on the buyers account, or not returned after the what=account_info request.

**Comment by alex-prog** [comment]
Hej...This is because your currency and the one you are buy has the same exchange rate. 

eg:
exchange rate -> 100 xxx = 100 yyy
offer             -> xxx will sell 5xxx
buy               -> yyy will buy 5xxx
Since the rate is the same, you need to pay 5xxx (this will be 5yyy), and you will get 5xxx = 5yyy.

So nothing will happen
